# btop theme adapted from Kitty palette

theme[main_bg]="#20000f"
theme[main_fg]="#ffedf2"

theme[title]="#ff6996"
theme[hi_fg]="#ff0055"

theme[selected_bg]="#3a1024"
theme[selected_fg]="#fff7f9"

theme[inactive_fg]="#a5979b"
theme[proc_misc]="#ffbbcf"

theme[cpu_box]="#980298"
theme[mem_box]="#980298"
theme[net_box]="#980298"
theme[proc_box]="#980298"

theme[div_line]="#6e2947"

theme[temp_start]="#5557f1"
theme[temp_mid]="#ff6996"
theme[temp_end]="#ff0055"

theme[cpu_start]="#5557f1"
theme[cpu_mid]="#ff6996"
theme[cpu_end]="#ff0055"

theme[free_start]="#8eff69"
theme[free_mid]="#b0ff96"
theme[free_end]="#8eff69"

theme[cached_start]="#85c2ff"
theme[cached_mid]="#5557f1"
theme[cached_end]="#85c2ff"

theme[available_start]="#8eff69"
theme[available_mid]="#b0ff96"
theme[available_end]="#8eff69"

theme[used_start]="#ff6996"
theme[used_mid]="#ff595f"
theme[used_end]="#ff0055"

theme[download_start]="#85c2ff"
theme[download_mid]="#5557f1"
theme[download_end]="#85c2ff"

theme[upload_start]="#e531cd"
theme[upload_mid]="#ff69c6"
theme[upload_end]="#ff0055"