foreground              #e4e1e9
background              #131318

# Black
color0  #1c252c
color8  #384148

# Red
color1  #e05f65
color9  #fc7b81

# Green
color2  #78dba9
color10 #94f7c5

# Yellow
color3  #f1cf8a
color11 #ffeba6

# Blue
color4  #70a5eb
color12 #8cc1ff

# Magenta
color5  #c68aee
color13 #e2a6ff

# Cyan
color6  #74bee9
color14 #90daff

# White
color7  #dee1e6
color15 #fafdff

# Cursor
cursor              #e4e1e9
cursor_text_color   #131318
cursor_trail_color  #c7c5d0

# Selection highlight
selection_foreground #c7c5d0
selection_background #46464f

# Borders
active_border_color   #bdc2ff
inactive_border_color #46464f

# URL
url_color #bdc2ff

# Tabs
active_tab_foreground   #262b61
active_tab_background   #bdc2ff
inactive_tab_foreground #c7c5d0
inactive_tab_background #46464f