#!/bin/sh
# Xsetup - run as root before the login dialog appears

xrandr --output DP-1 --primary --mode 1920x1080 --rate 200 --pos 0x0 --output HDMI-A-1 --mode 1920x1080 --rate 60 --right-of DP-1
(sleep 1 && xdotool mousemove 959 540 && xdotool mousemove 960 540) &