background_opacity          1
cursor_trail                1
window_padding_width        25
# Send a notification when a command takes more than 5 seconds in an unfocused window
notify_on_cmd_finish unfocused

include themes/Celestial.conf
