# general settings
background_opacity          1
cursor_trail                3
window_padding_width        25
# Send a notification when a command takes more than 5 seconds in an unfocused window
notify_on_cmd_finish unfocused 
# makes it so that it always show the 'tabs' bar even if there is only one tab
tab_bar_min_tabs 1

# Use theme
include themes/pinkpink.conf
#options: Celestial.conf // pinkpink.conf // literraly anything for default theme .conf //


# Use the regular version of nerdfont symbols instead of the mono one, bcz the mono one is too small
symbol_map U+e000-U+f8ff,U+f0000-U+ffffd,U+100000-U+10fffd Symbols Nerd Font

# Tab bar
tab_bar_min_tabs 1
tab_bar_edge bottom
tab_bar_style fade
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
# Ends Tab bar 

# BEGIN_KITTY_FONTS
#font_family      family="Rixlovefool Cyrillic Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Layouts
enabled_layouts tall,fat,grid,horizontal,vertical
map alt+s next_layout
map alt+h neighboring_window left
map alt+t neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down
# Layouts end